add_newline = false

[character]
success_symbol = "[➜](bold green)" 
error_symbol = "[➜](bold red)" 

[java]
disabled = true

[package]
disabled = true

[php]
disabled = true

[python]
disabled = true

[ruby]
disabled = true
